### ISSUE TITLE
EXIF data reading is broken with Pillow 3.0

### ISSUE THREAD

**Issue by saimn** [saimn/sigal#172]
It seems that Pillow 3.0 changes the format of EXIF data.
http://pillow.readthedocs.org/en/latest/releasenotes/3.0.0.html

With Pillow 3.0:
```
 'ExposureTime': (0.00100603,),
 'FNumber': (3.9,),
 'FileSource': (b'\x03',),
 'Flash': (16,),
 'FlashPixVersion': (b'0100',),
 'FocalLength': (11.5,),
 'FocalLengthIn35mmFilm': (76,),
 'GainControl': (0,),
 'ISOSpeedRatings': (50,),
```

With Pillow 2.9.0:
```
 'ExposureTime': (100603, 100000000),
 'FNumber': (39, 10),
 'FileSource': 3,
 'Flash': 16,
 'FlashPixVersion': b'0100',
 'FocalLength': (115, 10),
 'FocalLengthIn35mmFilm': 76,
 'GainControl': 0,
 'ISOSpeedRatings': 50,
```

**Comment by saimn** [comment]
Fixing this is straightforward, but there is a more serious issue with the GPSInfo which is broken in Pillow 3.0. Let's hope it will be fixed in the next bugfix release (https://github.com/python-pillow/Pillow/issues/1477)

**Comment by willmcgugan** [comment]
What's the verdict on this one? Is the format change intentional or a bug? A tuple of one value is a little odd.

I'd recommend keeping fractions as list of two values, rather than converting to a float. Photographers will want to see a photo had a shutter speed of 1/640, not 0.0015625. Working backwards would be a pain there.

Could you keep the `_getexif` method returning the same format as it did pre-3.0.0, for the sake of backwards compatibility. And add a `getexif` for any format changes?

**Comment by saimn** [comment]
I guess your message should be addressed to Pillow developers, there is nothing I can do about this on Sigal's side.

**Comment by willmcgugan** [comment]
My bad. I followed a link. Thought I was in the Pillow project.

**Comment by saxenanurag** [comment]
Any updates on this? I have temporarily switched to 2.9 to get GPSData from image. Thanks.

**Comment by saimn** [comment]
@saxenanurag No, it seems that nothing happened on Pillow side since a few weeks ...

**Comment by wiredfool** [comment]
For everyone who's interested in the exif handling in Pillow, Please test the new 3.1.0-rc1 release soon and give feedback.

**Comment by saimn** [comment]
@wiredfool Seems good, thanks !

**Comment by saimn** [comment]
Ref #189

**Comment by saimn** [comment]
Pillow 3.1.0 is out and this is fixed.
