### ISSUE TITLE
Deleted photos not removed from destination gallery and thumbs

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#276]
If I delete some photos in my source folder, a new index will be generated without those images, but the image files persist in the destination and thumb directories. Why not purge them on regenerations?

**Comment by saimn** [comment]
Hi @reagle ,
It is not done for several reasons: because in terms of performance doing this at each build would be bad, and for small enough galleries deleting the build directory is simple enough, and for my own usage I never really needed it. But I see how it could be useful to have, so I guess it could be an optional feature activated with `--clean` or `--purge` flag ?

**Comment by saimn** [comment]
And as a long standing issue :wink:  there is already an opened issue (let's continue the discussion there if you want) : #131
