### ISSUE TITLE
Unwanted numeric sort

### ISSUE THREAD

**Issue by bazuchan** [saimn/sigal#424]
After upgrading from 1.X to 2.1 sorting started to use numeic sort where it is not desired.

For exmaple albums 2021_01_16-a, 2021_01_2X-b, 2021_01_29-c is getting sorted in order:
2021_01_2X-b
2021_01_16-a
2021_01_29-c

**Comment by saimn** [comment]
It's not a numeric sort, #387 replaced the simple alphabetical sort with the more elaborated one from natsort (https://pypi.org/project/natsort/). Which should generally improve the sort results but in this case may not be the optimal one. I guess it would be good to open an issue on their repo to see if the result is expected in your case.

**Comment by bazuchan** [comment]
https://github.com/SethMMorton/natsort/issues/129

**Comment by bazuchan** [comment]
It was suggested not to use natsort in this case :)
Maybe configuration variable for sort type should be added?

**Comment by SethMMorton** [comment]
Hi, `natsort` developer here. One thing I can say having gone through the experience of implementing and maintaining `natsort` is that there is no such thing as a one-size-fits-all sort order definition - there can even be different opinions of how the same data set should be sorted. I do not know what this project is all about, but if having "properly" sorted data (for a given value of "properly") is important, then allowing the user some flexibility in to define what is "proper" may be useful.

**Comment by saimn** [comment]
Thanks for taking the time to comment here @SethMMorton. Sigal is a photo gallery and natsort is used to sort albums and photos, by default on their name which can be any string, or optionally on any metadata. So when someone proposed to use natsort that seemed a good idea as it should provide a better sort on most cases. But as you say it's difficult to define what a proper sort is in a general case.

@bazuchan - I would prefer to avoid another setting since natsort is used in a few places (https://github.com/saimn/sigal/pull/387/files#diff-a52c755961dc45c98fa8799f59ecbfb7a805911ece9a79585408e3552abc2f5f), handling the different cases with the 2 sort algorithms will be messy...

**Comment by bazuchan** [comment]
@saimn I didn't looked at plugin interface yet. Is it possible to write plugin to generate additional metadata key for albums and use it for sorting?

**Comment by saimn** [comment]
@bazuchan - Yes that could be an option. I guess it's doable with the `album_initialized` signal.
